web:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/cunobo_app
  volumes_from:
    - node
    - bundle
  #env_file: .env

bundle:
  image: busybox
  volumes:
    - .bundle:/bundle

node:
  image: busybox
  volumes:
    - node_modules:/node_modules

db:
  image: postgres:9.5.0
  ports:
    - "5432:5432"
  volumes:
    - .:/cunobo_app
