development: &default
  adapter: postgresql
  database: cunobo_app_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['CUNOBO_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['CUNOBO_DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: cunobo_app_development 
